const express=require('express'),db=require('../db');
const {buildTermReport}=require('../services/report-engine');
const {authenticate,roles,schoolBoundary}=require('../middleware/auth');
const router=express.Router();router.use(authenticate);
async function deliverSms({phone,message,school_id,learner_id}){
  const provider=String(process.env.SMS_PROVIDER||'').toUpperCase();
  if(provider==='AFRICASTALKING' && process.env.SMS_AFRICA_TALKING_USERNAME && process.env.SMS_AFRICA_TALKING_API_KEY){
    const base=String(process.env.SMS_AFRICA_TALKING_ENV||'live').toLowerCase()==='sandbox'?'https://api.sandbox.africastalking.com':'https://api.africastalking.com';
    const form=new URLSearchParams({username:process.env.SMS_AFRICA_TALKING_USERNAME,to:String(phone),message:String(message)});
    if(process.env.SMS_AFRICA_TALKING_SENDER_ID)form.set('from',process.env.SMS_AFRICA_TALKING_SENDER_ID);
    const rr=await fetch(`${base}/version1/messaging`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded',apiKey:process.env.SMS_AFRICA_TALKING_API_KEY},body:form});
    const data=await rr.json().catch(()=>({}));
    if(!rr.ok)throw new Error(`Africa's Talking returned ${rr.status}`);
    const recipient=data?.SMSMessageData?.Recipients?.[0];
    if(recipient && recipient.status && !/success|sent|queued/i.test(String(recipient.status)))throw new Error(String(recipient.status));
    return {status:'SENT',provider:'AFRICASTALKING',response:data};
  }
  if(process.env.SMS_WEBHOOK_URL){
    const rr=await fetch(process.env.SMS_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone,message,school_id,learner_id})});
    if(!rr.ok)throw new Error(`SMS webhook returned ${rr.status}`);
    return {status:'SENT',provider:'WEBHOOK'};
  }
  return {status:'QUEUED',provider:provider||'UNCONFIGURED'};
}

router.get('/:schoolId/parents',schoolBoundary,async(req,res)=>{try{const q=await db.query(`SELECT pg.*,count(lg.learner_id)::int learner_count FROM parent_guardians pg LEFT JOIN learner_guardians lg ON lg.parent_guardian_id=pg.id WHERE pg.school_id=$1 GROUP BY pg.id ORDER BY pg.last_name,pg.first_name`,[req.params.schoolId]);res.json(q.rows)}catch(e){res.status(500).json({error:'Unable to load parents'})}});
router.post('/:schoolId/parents',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','CLASS_TEACHER','SENIOR_TEACHER'),async(req,res)=>{try{const b=req.body;if(!String(b.first_name||'').trim()||!String(b.last_name||'').trim()||!String(b.phone||'').trim())return res.status(400).json({error:'Parent name and phone are required'});const q=await db.query(`INSERT INTO parent_guardians(school_id,first_name,last_name,relationship,phone,email,preferred_language,communication_consent,sms_enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.params.schoolId,String(b.first_name).trim(),String(b.last_name).trim(),b.relationship||null,String(b.phone).trim(),b.email||null,b.preferred_language||null,b.communication_consent!==false,b.sms_enabled!==false]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.post('/:schoolId/link',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','CLASS_TEACHER','SENIOR_TEACHER'),async(req,res)=>{try{const {learner_id,parent_guardian_id,is_primary}=req.body;const ok=(await db.query('SELECT 1 FROM learners WHERE id=$1 AND school_id=$2',[learner_id,req.params.schoolId])).rowCount&& (await db.query('SELECT 1 FROM parent_guardians WHERE id=$1 AND school_id=$2',[parent_guardian_id,req.params.schoolId])).rowCount;if(!ok)return res.status(404).json({error:'Learner or parent not found'});await db.query(`INSERT INTO learner_guardians(learner_id,parent_guardian_id,is_primary) VALUES($1,$2,$3) ON CONFLICT(learner_id,parent_guardian_id) DO UPDATE SET is_primary=EXCLUDED.is_primary`,[learner_id,parent_guardian_id,is_primary===true]);res.status(201).json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
router.get('/:schoolId/learner/:learnerId/parents',schoolBoundary,async(req,res)=>{try{const q=await db.query(`SELECT pg.*,lg.is_primary FROM parent_guardians pg JOIN learner_guardians lg ON lg.parent_guardian_id=pg.id WHERE pg.school_id=$1 AND lg.learner_id=$2 ORDER BY lg.is_primary DESC,pg.last_name`,[req.params.schoolId,req.params.learnerId]);res.json(q.rows)}catch(e){res.status(500).json({error:'Unable to load learner parents'})}});
router.post('/:schoolId/send',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const b=req.body;let guardians=[];if(b.learner_id){guardians=(await db.query(`SELECT pg.id,pg.phone FROM parent_guardians pg JOIN learner_guardians lg ON lg.parent_guardian_id=pg.id WHERE pg.school_id=$1 AND lg.learner_id=$2 AND pg.is_active AND pg.sms_enabled AND pg.communication_consent`,[req.params.schoolId,b.learner_id])).rows;}else if(b.parent_guardian_ids?.length){guardians=(await db.query(`SELECT id,phone FROM parent_guardians WHERE school_id=$1 AND id=ANY($2::uuid[]) AND is_active AND sms_enabled AND communication_consent`,[req.params.schoolId,b.parent_guardian_ids])).rows;}else return res.status(400).json({error:'Select a learner or parent recipients'});const body=String(b.message||'').trim();if(!body)return res.status(400).json({error:'Message is required'});const out=[];for(const g of guardians){let status='QUEUED',provider=process.env.SMS_PROVIDER||'UNCONFIGURED',failure=null;try{const d=await deliverSms({phone:g.phone,message:body,school_id:req.params.schoolId,learner_id:b.learner_id||null});status=d.status;provider=d.provider||provider;}catch(e){status='FAILED';failure=e.message;}const q=await db.query(`INSERT INTO communication_messages(school_id,learner_id,parent_guardian_id,channel,message_type,body,status,provider,error_message,created_by) VALUES($1,$2,$3,'SMS',$4,$5,$6,$7,$8,$9) RETURNING *`,[req.params.schoolId,b.learner_id||null,g.id,b.message_type||'SCHOOL_MESSAGE',body,status,provider,failure,req.user.user_id]);out.push(q.rows[0]);}res.status(201).json({queued:out.filter(x=>x.status==='QUEUED').length,sent:out.filter(x=>x.status==='SENT').length,failed:out.filter(x=>x.status==='FAILED').length,messages:out,notice:process.env.SMS_PROVIDER?'SMS processed through the configured provider.':'Queued locally; configure an SMS provider before production sending.'})}catch(e){res.status(400).json({error:e.message})}});
router.post('/:schoolId/results-ready',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const b=req.body;if(!b.learner_id||!b.academic_year_id||!b.term_id)return res.status(400).json({error:'Learner, academic year and term are required'});const report=await buildTermReport(req.params.schoolId,b.learner_id,b.academic_year_id,b.term_id);if(!report)return res.status(404).json({error:'Report not found'});const guardians=(await db.query(`SELECT pg.id,pg.phone FROM parent_guardians pg JOIN learner_guardians lg ON lg.parent_guardian_id=pg.id WHERE pg.school_id=$1 AND lg.learner_id=$2 AND pg.is_active AND pg.sms_enabled AND pg.communication_consent`,[req.params.schoolId,b.learner_id])).rows;const body=`${report.school_name}: ${report.learner_name}'s ${report.term_name||'term'} results are ready. Average: ${report.overall_average==null?'—':Number(report.overall_average).toFixed(2)}. Log in to PRO-MARK to view the full report.`;const out=[];for(const g of guardians){let status='QUEUED',provider=process.env.SMS_PROVIDER||'UNCONFIGURED',failure=null;try{const d=await deliverSms({phone:g.phone,message:body,school_id:req.params.schoolId,learner_id:b.learner_id});status=d.status;provider=d.provider||provider;}catch(e){status='FAILED';failure=e.message;}const q=await db.query(`INSERT INTO communication_messages(school_id,learner_id,parent_guardian_id,channel,message_type,body,status,provider,error_message,created_by) VALUES($1,$2,$3,'SMS','RESULTS_READY',$4,$5,$6,$7,$8) RETURNING *`,[req.params.schoolId,b.learner_id,g.id,body,status,provider,failure,req.user.user_id]);out.push(q.rows[0]);}res.status(201).json({queued:out.filter(x=>x.status==='QUEUED').length,sent:out.filter(x=>x.status==='SENT').length,failed:out.filter(x=>x.status==='FAILED').length,messages:out,notice:process.env.SMS_PROVIDER?'SMS processed through the configured provider.':'Queued locally; configure an SMS provider before production sending.'})}catch(e){res.status(400).json({error:e.message})}});
router.get('/:schoolId/history',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER'),async(req,res)=>{try{const q=await db.query(`SELECT cm.*,pg.first_name parent_first_name,pg.last_name parent_last_name,pg.phone FROM communication_messages cm LEFT JOIN parent_guardians pg ON pg.id=cm.parent_guardian_id WHERE cm.school_id=$1 ORDER BY cm.created_at DESC LIMIT 200`,[req.params.schoolId]);res.json(q.rows)}catch(e){res.status(500).json({error:'Unable to load communication history'})}});

// Grade/class results publication: builds the learner result SMS from the published assessment context.
router.get('/:schoolId/grade-roster',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const sid=req.params.schoolId,y=req.query.academic_year_id;const q=await db.query(`SELECT lv.id level_id,lv.name level_name,COUNT(DISTINCT l.id)::int learners,COUNT(DISTINCT pg.id)::int parents_with_phone FROM school_levels lv JOIN classes c ON c.school_level_id=lv.id AND c.school_id=lv.school_id LEFT JOIN learner_enrollments e ON e.class_id=c.id AND e.academic_year_id=$2 AND e.school_id=$1 AND COALESCE(e.status,'ACTIVE')='ACTIVE' LEFT JOIN learners l ON l.id=e.learner_id AND l.school_id=$1 LEFT JOIN learner_guardians lg ON lg.learner_id=l.id LEFT JOIN parent_guardians pg ON pg.id=lg.parent_guardian_id AND pg.is_active AND pg.sms_enabled AND pg.communication_consent WHERE lv.school_id=$1 AND lv.is_active GROUP BY lv.id,lv.name ORDER BY lv.sort_order,lv.name`,[sid,y]);res.json(q.rows)}catch(e){res.status(400).json({error:e.message})}});
router.get('/:schoolId/grade-learners',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const sid=req.params.schoolId,y=req.query.academic_year_id,level=req.query.level_id;if(!y||!level)return res.status(400).json({error:'Academic year and grade are required'});const q=await db.query(`SELECT l.id learner_id,l.admission_no,l.first_name,l.middle_name,l.last_name,c.name class_name,c.stream,lv.name level_name,COALESCE(json_agg(DISTINCT jsonb_build_object('id',pg.id,'name',concat_ws(' ',pg.first_name,pg.last_name),'phone',pg.phone)) FILTER (WHERE pg.id IS NOT NULL),'[]') parents FROM learner_enrollments e JOIN learners l ON l.id=e.learner_id JOIN classes c ON c.id=e.class_id JOIN school_levels lv ON lv.id=c.school_level_id LEFT JOIN learner_guardians lg ON lg.learner_id=l.id LEFT JOIN parent_guardians pg ON pg.id=lg.parent_guardian_id AND pg.is_active AND pg.sms_enabled AND pg.communication_consent WHERE e.school_id=$1 AND e.academic_year_id=$2 AND c.school_level_id=$3 AND COALESCE(e.status,'ACTIVE')='ACTIVE' GROUP BY l.id,c.id,lv.id ORDER BY c.name,c.stream,l.last_name,l.first_name`,[sid,y,level]);res.json(q.rows)}catch(e){res.status(400).json({error:e.message})}});
router.post('/:schoolId/publish-grade-results',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const sid=req.params.schoolId,b=req.body||{};if(!b.academic_year_id||!b.term_id||!b.level_id)return res.status(400).json({error:'Academic year, term and grade are required'});const learners=(await db.query(`SELECT DISTINCT l.id,l.first_name,l.middle_name,l.last_name FROM learner_enrollments e JOIN learners l ON l.id=e.learner_id JOIN classes c ON c.id=e.class_id WHERE e.school_id=$1 AND e.academic_year_id=$2 AND c.school_level_id=$3 AND COALESCE(e.status,'ACTIVE')='ACTIVE'`,[sid,b.academic_year_id,b.level_id])).rows;let queued=0,skipped=0,failed=0;for(const l of learners){const report=await buildTermReport(sid,l.id,b.academic_year_id,b.term_id);if(!report){skipped++;continue}const guardians=(await db.query(`SELECT pg.id,pg.phone FROM parent_guardians pg JOIN learner_guardians lg ON lg.parent_guardian_id=pg.id WHERE pg.school_id=$1 AND lg.learner_id=$2 AND pg.is_active AND pg.sms_enabled AND pg.communication_consent AND COALESCE(trim(pg.phone),'')<>''`,[sid,l.id])).rows;if(!guardians.length){skipped++;continue}const subjectSummary=(report.subjects||[]).map(x=>`${x.subject_code||x.subject_name}:${x.average==null?'—':Number(x.average).toFixed(1)}${x.grade?'/'+x.grade:''}`).join(', ');const body=String(b.message_template||`${report.school_name}: ${report.learner_name} ${report.term_name||'term'} results. Average ${report.overall_average==null?'—':Number(report.overall_average).toFixed(2)}, grade ${report.overall_grade||'—'}. Marks: ${subjectSummary||'See portal for full report.'}`).replaceAll('{learner}',report.learner_name).replaceAll('{average}',report.overall_average==null?'—':Number(report.overall_average).toFixed(2)).replaceAll('{grade}',report.overall_grade||'—').replaceAll('{marks}',subjectSummary);for(const g of guardians){let status='QUEUED',provider=process.env.SMS_PROVIDER||'UNCONFIGURED',reason=null;try{const d=await deliverSms({phone:g.phone,message:body,school_id:sid,learner_id:l.id});status=d.status;provider=d.provider;}catch(e){reason=e.message;status='FAILED';failed++;}await db.query(`INSERT INTO communication_messages(school_id,learner_id,parent_guardian_id,channel,message_type,body,status,provider,failure_reason,created_by,sent_at) VALUES($1,$2,$3,'SMS','PUBLISHED_RESULTS',$4,$5,$6,$7,$8,CASE WHEN $5='SENT' THEN now() ELSE NULL END)`,[sid,l.id,g.id,body,status,provider,reason,req.user.user_id]);if(status==='SENT'||status==='QUEUED')queued++;}}res.status(201).json({learners:learners.length,queued,skipped,failed,message:(String(process.env.SMS_PROVIDER||'').toUpperCase()==='AFRICASTALKING'&&process.env.SMS_AFRICA_TALKING_API_KEY)?"Results sent through Africa's Talking SMS.":(process.env.SMS_WEBHOOK_URL?'Results sent through the configured SMS webhook.':'Results queued safely; configure an SMS provider for live delivery.')});}catch(e){res.status(400).json({error:e.message})}});
// Deep academic analytics for the selected grade/class context.
router.get('/:schoolId/analytics',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER','DEPUTY_HEADTEACHER','SENIOR_TEACHER'),async(req,res)=>{
 try{
  const sid=req.params.schoolId,{academic_year_id:y,term_id:t,level_id:level,class_id:cls}=req.query;
  if(!y||!t)return res.status(400).json({error:'Academic year and term are required'});
  const term=(await db.query(`SELECT id,term_no,name FROM terms WHERE id=$1 AND school_id=$2`,[t,sid])).rows[0];
  if(!term)return res.status(404).json({error:'Term not found'});
  const filters=[];const params=[sid,y,t];let n=4;
  if(level){filters.push(`c.school_level_id=$${n++}`);params.push(level)}
  if(cls){filters.push(`m.class_id=$${n++}`);params.push(cls)}
  const where=filters.length?' AND '+filters.join(' AND '):'';
  const overall=(await db.query(`SELECT COUNT(DISTINCT m.learner_id)::int learners,COUNT(m.id)::int mark_entries,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) mean_mark,ROUND((percentile_cont(0.5) WITHIN GROUP (ORDER BY (m.mark/NULLIF(a.max_mark,0))*100.0))::numeric,2) median_mark,ROUND(MIN((m.mark/NULLIF(a.max_mark,0))*100.0),2) min_mark,ROUND(MAX((m.mark/NULLIF(a.max_mark,0))*100.0),2) max_mark FROM marks m JOIN assessments a ON a.id=m.assessment_id JOIN classes c ON c.id=m.class_id WHERE m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL${where}`,params)).rows[0];
  const expected=(await db.query(`SELECT COUNT(DISTINCT e.learner_id)*COUNT(DISTINCT tsa.subject_id)*COUNT(DISTINCT a.id)::int expected_mark_entries
    FROM learner_enrollments e JOIN classes c ON c.id=e.class_id
    JOIN teacher_subject_assignments tsa ON tsa.school_id=e.school_id AND tsa.class_id=e.class_id AND tsa.academic_year_id=$2 AND (tsa.term_id=$3 OR tsa.term_id IS NULL) AND COALESCE(tsa.is_active,true)=true
    JOIN assessments a ON a.school_id=e.school_id AND a.academic_year_id=$2 AND a.term_id=$3
    WHERE e.school_id=$1 AND e.academic_year_id=$2 AND COALESCE(e.status,'ACTIVE')='ACTIVE'${level?' AND c.school_level_id=$4':''}${cls?` AND c.id=$${level?5:4}`:''}`,[sid,y,t,...(level?[level]:[]),...(cls?[cls]:[])])).rows[0];
  overall.expected_mark_entries=Number(expected?.expected_mark_entries||0);
  const subjects=(await db.query(`SELECT s.id,s.code,s.name,COUNT(m.id)::int entries,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average,ROUND(MIN((m.mark/NULLIF(a.max_mark,0))*100.0),2) min_mark,ROUND(MAX((m.mark/NULLIF(a.max_mark,0))*100.0),2) max_mark,
    COALESCE((SELECT CONCAT_WS(' ',th.first_name,th.last_name) FROM teacher_subject_assignments tsa JOIN teachers th ON th.id=tsa.teacher_id WHERE tsa.school_id=$1 AND tsa.subject_id=s.id AND tsa.academic_year_id=$2 AND (tsa.term_id=$3 OR tsa.term_id IS NULL) AND COALESCE(tsa.is_active,true)=true ${cls?`AND tsa.class_id=$${level?5:4}`:''} AND COALESCE(th.is_active,true)=true AND NOT (upper(trim(coalesce(th.first_name,''))) IN ('TEACHER','ADMIN') OR upper(trim(coalesce(th.last_name,''))) IN ('TEACHER','ADMIN') OR upper(trim(coalesce(th.staff_no,''))) IN ('TEACHER','ADMIN','MR.TEACHER','MR. TEACHER')) ORDER BY (tsa.term_id IS NOT NULL) DESC,tsa.created_at DESC,tsa.id DESC LIMIT 1),'Not assigned') teacher_name
    FROM marks m JOIN assessments a ON a.id=m.assessment_id JOIN subjects s ON s.id=m.subject_id JOIN classes c ON c.id=m.class_id WHERE m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL${where} GROUP BY s.id,s.code,s.name ORDER BY average DESC NULLS LAST`,params)).rows;
  const classes=(await db.query(`SELECT c.id,c.name,c.stream,COUNT(DISTINCT m.learner_id)::int learners,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average FROM classes c LEFT JOIN marks m ON m.class_id=c.id AND m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL JOIN assessments a ON a.id=m.assessment_id WHERE c.school_id=$1 ${level?'AND c.school_level_id=$4':''}${cls?` AND c.id=$${level?5:4}`:''} GROUP BY c.id,c.name,c.stream ORDER BY average DESC NULLS LAST`,params)).rows;
  const streams=(await db.query(`SELECT COALESCE(NULLIF(c.stream,''),'Main') stream,c.name class_name,COUNT(DISTINCT m.learner_id)::int learners,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average FROM classes c JOIN marks m ON m.class_id=c.id AND m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL JOIN assessments a ON a.id=m.assessment_id WHERE c.school_id=$1${level?' AND c.school_level_id=$4':''}${cls?` AND c.id=$${level?5:4}`:''} GROUP BY c.id,c.name,c.stream ORDER BY average DESC NULLS LAST`,params)).rows;
  const gender=(await db.query(`SELECT COALESCE(NULLIF(l.gender,''),'Not specified') gender,COUNT(DISTINCT l.id)::int learners,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average FROM learners l JOIN marks m ON m.learner_id=l.id JOIN assessments a ON a.id=m.assessment_id JOIN classes c ON c.id=m.class_id WHERE l.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL${where} GROUP BY COALESCE(NULLIF(l.gender,''),'Not specified') ORDER BY average DESC`,params)).rows;
  const learnerSubjects=(await db.query(`SELECT l.id learner_id,CONCAT_WS(' ',l.first_name,l.middle_name,l.last_name) learner_name,l.gender,c.name class_name,c.stream,s.id subject_id,s.name subject_name,AVG((m.mark/NULLIF(a.max_mark,0))*100.0) average FROM marks m JOIN learners l ON l.id=m.learner_id JOIN assessments a ON a.id=m.assessment_id JOIN subjects s ON s.id=m.subject_id JOIN classes c ON c.id=m.class_id WHERE m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL${where} GROUP BY l.id,l.first_name,l.middle_name,l.last_name,l.gender,c.name,c.stream,s.id,s.name`,params)).rows;
  const grading=(await db.query(`SELECT gb.label,gb.min_mark,gb.max_mark,gb.points,gb.descriptor,gb.remark FROM grading_systems gs JOIN grading_bands gb ON gb.grading_system_id=gs.id WHERE gs.school_id=$1 AND gs.is_active=true ORDER BY gb.min_mark DESC`,[sid])).rows;
  const gradeFor=v=>{const n=Number(v);if(!Number.isFinite(n))return null;const competency=grading.filter(g=>['EE','ME','AE','BE'].includes(String(g.label||'').toUpperCase()));if(competency.length>=4)return competency.find(g=>n>=Number(g.min_mark)&&n<=Number(g.max_mark))||null;return n>=80?{label:'EE',points:4,min_mark:80,max_mark:100,descriptor:'Exceeds Expectations'}:n>=60?{label:'ME',points:3,min_mark:60,max_mark:79.99,descriptor:'Meets Expectations'}:n>=40?{label:'AE',points:2,min_mark:40,max_mark:59.99,descriptor:'Approaches Expectations'}:{label:'BE',points:1,min_mark:0,max_mark:39.99,descriptor:'Below Expectations'};};
  const learnerMap=new Map();for(const r of learnerSubjects){if(!learnerMap.has(r.learner_id))learnerMap.set(r.learner_id,{learner_id:r.learner_id,learner_name:r.learner_name,gender:r.gender,class_name:r.class_name,stream:r.stream,subjects:[]});learnerMap.get(r.learner_id).subjects.push({subject_id:r.subject_id,subject_name:r.subject_name,average:Number(r.average)});}
  const learnerAverages=[...learnerMap.values()].map(l=>({...l,average:l.subjects.length?l.subjects.reduce((a,b)=>a+b.average,0)/l.subjects.length:null}));
  const distribution={};for(const l of learnerAverages){const g=gradeFor(l.average);if(g)distribution[g.label]=(distribution[g.label]||0)+1;}
  let targetRows=[];
  try{targetRows=(await db.query(`SELECT s.id subject_id,s.name subject_name,AVG(ac.target_mark) target_mark,AVG(x.average) achievement FROM assessment_configurations ac JOIN subjects s ON s.id=ac.subject_id JOIN LATERAL (SELECT AVG((m.mark/NULLIF(a.max_mark,0))*100.0) average FROM marks m JOIN assessments a ON a.id=m.assessment_id WHERE m.school_id=ac.school_id AND m.subject_id=ac.subject_id AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL) x ON true WHERE ac.school_id=$1 AND ac.target_mark IS NOT NULL GROUP BY s.id,s.name ORDER BY achievement DESC NULLS LAST`,[sid,y,t])).rows}catch{}
  // Compare with the immediately preceding term in the same academic year where one exists.
  const prev=(await db.query(`SELECT id,term_no,name FROM terms WHERE school_id=$1 AND academic_year_id=$2 AND term_no<$3 ORDER BY term_no DESC LIMIT 1`,[sid,y,term.term_no])).rows[0]||null;
  let progress=[];
  let deviations=[];
  if(prev){
    progress=(await db.query(`SELECT l.id learner_id,CONCAT_WS(' ',l.first_name,l.middle_name,l.last_name) learner_name,ROUND(AVG(CASE WHEN m.term_id=$3 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END),2) current_average,ROUND(AVG(CASE WHEN m.term_id=$4 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END),2) previous_average FROM learners l JOIN marks m ON m.learner_id=l.id JOIN assessments a ON a.id=m.assessment_id JOIN classes c ON c.id=m.class_id WHERE m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id IN ($3,$4) AND m.mark IS NOT NULL${level?' AND c.school_level_id=$5':''}${cls?` AND c.id=$${level?6:5}`:''} GROUP BY l.id,l.first_name,l.middle_name,l.last_name ORDER BY (AVG(CASE WHEN m.term_id=$3 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END)-AVG(CASE WHEN m.term_id=$4 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END)) DESC LIMIT 20`,[sid,y,t,prev.id,...(level?[level]:[]),...(cls?[cls]:[])])).rows;
    deviations=(await db.query(`SELECT s.id subject_id,s.name subject_name,ROUND(AVG(CASE WHEN m.term_id=$3 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END),2) current_average,ROUND(AVG(CASE WHEN m.term_id=$4 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END),2) previous_average FROM marks m JOIN assessments a ON a.id=m.assessment_id JOIN subjects s ON s.id=m.subject_id JOIN classes c ON c.id=m.class_id WHERE m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id IN ($3,$4) AND m.mark IS NOT NULL${level?' AND c.school_level_id=$5':''}${cls?` AND c.id=$${level?6:5}`:''} GROUP BY s.id,s.name ORDER BY (AVG(CASE WHEN m.term_id=$3 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END)-AVG(CASE WHEN m.term_id=$4 THEN (m.mark/NULLIF(a.max_mark,0))*100.0 END)) DESC`,[sid,y,t,prev.id,...(level?[level]:[]),...(cls?[cls]:[])])).rows.map(x=>({...x,deviation:x.current_average==null||x.previous_average==null?null:Number(x.current_average)-Number(x.previous_average)}));
  }
  const bestAcross=(await db.query(`SELECT l.id learner_id,CONCAT_WS(' ',l.first_name,l.middle_name,l.last_name) learner_name,c.name class_name,c.stream,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average FROM learners l JOIN marks m ON m.learner_id=l.id JOIN assessments a ON a.id=m.assessment_id JOIN classes c ON c.id=m.class_id WHERE l.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL GROUP BY l.id,l.first_name,l.middle_name,l.last_name,c.name,c.stream ORDER BY average DESC,l.last_name,l.first_name LIMIT 20`,[sid,y,t])).rows;
  const assessmentSummary=(await db.query(`SELECT a.id,a.name,a.assessment_type,a.assessment_order,COUNT(m.id)::int entries,ROUND(AVG((m.mark/NULLIF(a.max_mark,0))*100.0),2) average FROM assessments a LEFT JOIN marks m ON m.assessment_id=a.id AND m.school_id=$1 AND m.academic_year_id=$2 AND m.term_id=$3 AND m.mark IS NOT NULL WHERE a.school_id=$1 AND a.academic_year_id=$2 AND a.term_id=$3 GROUP BY a.id,a.name,a.assessment_type,a.assessment_order ORDER BY a.assessment_order,a.created_at,a.name`,[sid,y,t])).rows;
  res.json({term,overall,subjects:subjects.map(x=>({...x,grade:gradeFor(x.average)?.label||''})),classes,streams,gender,grade_distribution:distribution,grading_bands:grading,target_vs_achievement:targetRows.map(x=>({...x,target_mark:Number(x.target_mark),achievement:x.achievement==null?null:Number(x.achievement),variance:x.achievement==null?null:Number(x.achievement)-Number(x.target_mark)})),progress,deviations,best_learners_across_classes:bestAcross,assessment_summary:assessmentSummary,learner_averages:learnerAverages.sort((a,b)=>(b.average||-1)-(a.average||-1)).slice(0,20)});
 }catch(e){res.status(400).json({error:e.message})}});
module.exports=router;
