const express=require('express'),db=require('../db');
const {authenticate,roles,schoolBoundary}=require('../middleware/auth');
const {assertBelongs}=require('../services/tenant');
const router=express.Router();router.use(authenticate);
function validateBands(bands){if(!Array.isArray(bands)||!bands.length)throw Error('At least one grading band is required');const sorted=bands.map(b=>({label:String(b.label||'').trim(),min:Number(b.min_mark),max:Number(b.max_mark),points:Number(b.points||0),descriptor:String(b.descriptor||''),remark:String(b.remark||'')}));if(sorted.some(b=>!b.label||!Number.isFinite(b.min)||!Number.isFinite(b.max)||b.min>b.max))throw Error('Every grading band needs a label and valid min/max marks');sorted.sort((a,b)=>a.min-b.min);for(let i=1;i<sorted.length;i++)if(sorted[i].min>sorted[i-1].max+0.0001)throw Error('Grading bands contain a gap');return sorted;}
router.get('/:schoolId/systems',schoolBoundary,async(req,res)=>{try{const q=await db.query(`SELECT gs.*,COALESCE(json_agg(gb ORDER BY gb.min_mark DESC) FILTER(WHERE gb.id IS NOT NULL),'[]') bands FROM grading_systems gs LEFT JOIN grading_bands gb ON gb.grading_system_id=gs.id WHERE gs.school_id=$1 GROUP BY gs.id ORDER BY gs.name`,[req.params.schoolId]);res.json(q.rows)}catch(e){res.status(500).json({error:'Unable to load grading systems'});}});
router.post('/:schoolId/systems',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{const b=req.body,c=await db.pool.connect();try{const name=String(b.name||'').trim(),code=String(b.code||'').trim().toUpperCase(),bands=validateBands(b.bands);if(!name||!code)throw Error('Grading system name and code are required');await c.query('BEGIN');const s=(await c.query(`INSERT INTO grading_systems(school_id,name,code,description) VALUES($1,$2,$3,$4) RETURNING *`,[req.params.schoolId,name,code,String(b.description||'')])).rows[0];for(const x of bands)await c.query(`INSERT INTO grading_bands(grading_system_id,label,min_mark,max_mark,points,descriptor,remark) VALUES($1,$2,$3,$4,$5,$6,$7)`,[s.id,x.label,x.min,x.max,x.points,x.descriptor,x.remark]);await c.query('COMMIT');res.status(201).json(s);}catch(e){await c.query('ROLLBACK');res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'That grading system code already exists.':e.message});}finally{c.release();}});
router.post('/:schoolId/configurations',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{const b=req.body;try{await assertBelongs('grading_systems',b.grading_system_id,req.params.schoolId);for(const [t,k] of [['school_sections','section_id'],['school_levels','level_id'],['subjects','subject_id'],['assessments','assessment_id']])if(b[k]){if(t==='school_sections'){const q=await db.query('SELECT id FROM school_sections WHERE id=$1 AND school_id=$2',[b[k],req.params.schoolId]);if(!q.rows[0])throw Object.assign(new Error('Section does not belong to this school'),{status:403});}else await assertBelongs(t,b[k],req.params.schoolId);}const q=await db.query(`INSERT INTO assessment_configurations(school_id,section_id,level_id,subject_id,assessment_id,grading_system_id,include_in_term_average,include_in_merit) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.params.schoolId,b.section_id||null,b.level_id||null,b.subject_id||null,b.assessment_id||null,b.grading_system_id,b.include_in_term_average!==false,b.include_in_merit!==false]);res.status(201).json(q.rows[0]);}catch(e){res.status(e.status||400).json({error:e.message});}});
module.exports=router;
